Timeout with Refactored File Input Flags
raisebook/run-go-lambda pull request #3
Opened 2018-02-14 19:50 UTC by jdgiotta

- Added flags via cobra.Command library to handle both file input and timeout
- Updated Gopkg.lock file with new dependencies
- Updated example bash script

2018-02-15 01:57 UTC, joffotron requested changes
Hi! Thanks for your changes! 

In principle, they look good/useful, but there are a few things I'll need before I can merge. I'll add line comments for those

2018-02-15 01:58 UTC, joffotron commented on src/run-go-lambda/Gopkg.lock
Can we please add dependencies using dep by altering the .toml file (e.g. `dep ensure -add github.com/spf13/cobra`) rather than editing the lock file?

Also, I don't see any references to mousetrap in the code, is it required?

2018-02-15 01:59 UTC, joffotron commented on src/run-go-lambda/run-go-lambda.go
Can you please run `gofmt` or `goimports` over the code? Looks like the standard spacing has got messed up here

2018-02-15 02:02 UTC, joffotron commented on src/run-go-lambda/run-go-lambda.go
> +    /*if err != nil { # TODO handle error
These might be better left in, we can bomb out here okay

2018-02-15 22:20 UTC, jdgiotta commented on src/run-go-lambda/Gopkg.lock
@joffotron I believe cobra is using it https://github.com/spf13/cobra/search?utf8=%E2%9C%93&q=mousetrap&type=

2018-02-15 22:24 UTC, jdgiotta commented
@joffotron I've made those requested changes

2018-02-16 01:18 UTC, joffotron commented on src/run-go-lambda/Gopkg.lock
Ah yep, cool, no problem 👍

2018-02-16 01:18 UTC, joffotron approved these changes

2018-02-16 01:18 UTC, merged

2018-02-16 01:19 UTC, joffotron commented
Thanks again so much for your contribution :)